CREATE DATABASE IF NOT EXISTS chongwu;
CREATE TABLE IF NOT EXISTS messages(
id int AUTO_INCREMENTS NOT NULL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
message VARCHAR(100) NOT NULL,
create_at VARCHAR(100) NOT NULL
)
CREATE TABLE IF NOT EXISTS pet(
id int AUTO_INCREMENTS NOT NULL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
age int NOT NULL,
sex VARCHAR(30) NOT NULL,
species VARCHAR(30) NOT NULL,
modelnumber VARCHAR(100) NOT NULL,
photo VARCHAR(30) LONGBLOB
)
CREATE TABLE IF NOT EXISTS users(
id int AUTO_INCREMENTS NOT NULL PRIMARY KEY,
username VARCHAR(40) NOT NULL,
password VARCHAR(40) NOT NULL,
hobby VARCHAR(100) NOT NULL,
home VARCHAR(100) NOT NULL,
avatar MEDIUMBLOB NOT NULL,
pet VARCHAR(100) NOT NULL
)